# MySQL TiDB 解析器配置文件
parser:
  # 启用 TiDB 解析器作为默认 MySQL 解析器
  enable_tidb_parser: true
  # 禁用 PostgreSQL 解析器
  enable_postgresql_parser: false
  # 当解析失败时是否回退到原始解析器
  fallback_to_original: true
  # 启用性能基准测试
  enable_benchmarking: true
  # 记录解析错误
  log_parsing_errors: true

# MySQL 特定配置
mysql:
  # 启用 MySQL 特定功能
  enableAdvancedFeatures: true
  # 支持 MySQL 方言
  dialect: "mysql"
  # 默认字符集
  charset: "utf8mb4"
  # 支持的 MySQL 版本
  version: "8.0"
  
  # MySQL 特有语法支持
  features:
    # 支持反引号标识符
    backtickIdentifiers: true
    # 支持 AUTO_INCREMENT
    autoIncrement: true
    # 支持 MySQL 风格的 LIMIT offset, count
    mysqlLimitSyntax: true
    # 支持 MySQL 特有函数
    mysqlFunctions: true
    # 支持 MySQL 存储引擎语法
    storageEngines: true

# 数据源配置示例（可选）
datasources:
  mysql_master:
    driver_name: "mysql"
    url: "user:password@tcp(localhost:3306)/sharding_db?charset=utf8mb4&parseTime=True&loc=Local"
    max_idle: 10
    max_open: 100
    conn_max_lifetime: 300
  
  mysql_slave:
    driver_name: "mysql"
    url: "user:password@tcp(localhost:3307)/sharding_db?charset=utf8mb4&parseTime=True&loc=Local"
    max_idle: 5
    max_open: 50
    conn_max_lifetime: 300

# 分片规则配置示例（可选）
sharding_rules:
  tables:
    users:
      actual_data_nodes: "mysql_master.users_${0..1}"
      database_strategy:
        sharding_column: "user_id"
        algorithm: "user_id % 2"
      table_strategy:
        sharding_column: "user_id"
        algorithm: "user_id % 2"
    
    orders:
      actual_data_nodes: "mysql_master.orders_${0..3}"
      database_strategy:
        sharding_column: "user_id"
        algorithm: "user_id % 2"
      table_strategy:
        sharding_column: "order_id"
        algorithm: "order_id % 4"

# 读写分离配置示例（可选）
read_write_splits:
  mysql_rw:
    write_data_source: "mysql_master"
    read_data_sources: ["mysql_slave"]
    load_balance_algorithm: "round_robin"

# 日志配置
logging:
  level: "info"
  enable_sql_logging: true
  enable_performance_logging: true